logging:
  level:
    com.inventory: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  file:
    name: logs/application.log

# Custom loggers for different purposes
custom:
  logging:
    api-log: logs/api-requests.log
    app-log: logs/application.log
